package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1


import Services.DaoService;
import Services.SessionService;
import java.util.HashSet;
import java.util.Set;
import javafx.beans.DefaultProperty;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Barangs generated by hbm2java
 */
@Entity
@Table(name = "barangs")
public class Barangs implements DaoService{


     @Id
     @GeneratedValue(strategy=GenerationType.AUTO)
     private Integer id;
     @OneToOne(fetch = FetchType.EAGER)
     @JoinColumn(name = "satuan_id")
     private Satuans satuans;
     private String kode_barang;
     private int harga;
     private Integer stok;
     private String nama_barang;
     private Integer deleted = 0;

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
    public Barangs() {
    }

	
    public Barangs(Satuans satuans, String kodeBarang, int harga, Integer stok, String namaBarang) {
        this.deleted = 0;
       this.satuans = satuans;
       this.kode_barang = kodeBarang;
       this.harga = harga;
       this.stok = stok;
       this.nama_barang = namaBarang;
    }
   public String getSatuan(){
       return satuans.getNamaSatuan();
   }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Satuans getSatuans() {
        return this.satuans;
    }
    
    public void setSatuans(Satuans satuans) {
        this.satuans = satuans;
    }
    public String getKode_barang() {
        return this.kode_barang;
    }
    
    public void setKode_barang(String kode_barang) {
        this.kode_barang = kode_barang;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }
    public Integer getStok() {
        return this.stok;
    }
    
    public void setStok(Integer stok) {
        this.stok = stok;
    }
    public String getNama_barang() {
        return this.nama_barang;
    }
    
    public void setNama_barang(String nama_barang) {
        this.nama_barang = nama_barang;
    }

    @Override
    public void Save() {
        SessionService.getInstance().getSession().beginTransaction();
        SessionService.getInstance().getSession().save(this);
        SessionService.getInstance().getSession().getTransaction().commit();
    }

    @Override
    public void Update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void Delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



}


