package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1


import Services.SessionService;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Satuans generated by hbm2java
 */
@Entity
@Table(name = "satuans")
public class Satuans {


     @Id
     private Integer id;
     private String namaSatuan;

    public Satuans() {
    }

	
    public Satuans(String namaSatuan) {
        this.namaSatuan = namaSatuan;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaSatuan() {
        return this.namaSatuan;
    }
    
    public void setNamaSatuan(String namaSatuan) {
        this.namaSatuan = namaSatuan;
    }
    public static List<Satuans> fetchData(){
        return SessionService.getInstance().getSession().createCriteria(Satuans.class).list();
    }



}


