package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TempTransaksis generated by hbm2java
 */
public class TempTransaksis  implements java.io.Serializable {


     private Integer id;
     private Date tanggalTransaksi;
     private Integer totalHarga;
     private int status;
     private Date createdAt;
     private Set tempTransaksiDetailses = new HashSet(0);

    public TempTransaksis() {
    }

	
    public TempTransaksis(Date tanggalTransaksi, int status, Date createdAt) {
        this.tanggalTransaksi = tanggalTransaksi;
        this.status = status;
        this.createdAt = createdAt;
    }
    public TempTransaksis(Date tanggalTransaksi, Integer totalHarga, int status, Date createdAt, Set tempTransaksiDetailses) {
       this.tanggalTransaksi = tanggalTransaksi;
       this.totalHarga = totalHarga;
       this.status = status;
       this.createdAt = createdAt;
       this.tempTransaksiDetailses = tempTransaksiDetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTanggalTransaksi() {
        return this.tanggalTransaksi;
    }
    
    public void setTanggalTransaksi(Date tanggalTransaksi) {
        this.tanggalTransaksi = tanggalTransaksi;
    }
    public Integer getTotalHarga() {
        return this.totalHarga;
    }
    
    public void setTotalHarga(Integer totalHarga) {
        this.totalHarga = totalHarga;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getTempTransaksiDetailses() {
        return this.tempTransaksiDetailses;
    }
    
    public void setTempTransaksiDetailses(Set tempTransaksiDetailses) {
        this.tempTransaksiDetailses = tempTransaksiDetailses;
    }




}


