package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1



/**
 * TempTransaksiDetails generated by hbm2java
 */
public class TempTransaksiDetails  implements java.io.Serializable {


     private Integer id;
     private Barangs barangs;
     private TempTransaksis tempTransaksis;
     private int jumlahBarang;
     private int totalHarga;

    public TempTransaksiDetails() {
    }

	
    public TempTransaksiDetails(int jumlahBarang, int totalHarga) {
        this.jumlahBarang = jumlahBarang;
        this.totalHarga = totalHarga;
    }
    public TempTransaksiDetails(Barangs barangs, TempTransaksis tempTransaksis, int jumlahBarang, int totalHarga) {
       this.barangs = barangs;
       this.tempTransaksis = tempTransaksis;
       this.jumlahBarang = jumlahBarang;
       this.totalHarga = totalHarga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Barangs getBarangs() {
        return this.barangs;
    }
    
    public void setBarangs(Barangs barangs) {
        this.barangs = barangs;
    }
    public TempTransaksis getTempTransaksis() {
        return this.tempTransaksis;
    }
    
    public void setTempTransaksis(TempTransaksis tempTransaksis) {
        this.tempTransaksis = tempTransaksis;
    }
    public int getJumlahBarang() {
        return this.jumlahBarang;
    }
    
    public void setJumlahBarang(int jumlahBarang) {
        this.jumlahBarang = jumlahBarang;
    }
    public int getTotalHarga() {
        return this.totalHarga;
    }
    
    public void setTotalHarga(int totalHarga) {
        this.totalHarga = totalHarga;
    }




}


