package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Transaksis generated by hbm2java
 */
@Entity
@Table(name = "transaksis")
public class Transaksis  {


     @Id
          @GeneratedValue(strategy=GenerationType.AUTO)
     private Integer id;
     private Date tanggal_transaksi;
     private Integer total_harga;
      @OneToMany(
        cascade = CascadeType.ALL,
        mappedBy = "transaksis",
        orphanRemoval = true
    )

     private List<TransaksiDetails> transaksiDetailses = new ArrayList<TransaksiDetails>();
    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
    public Transaksis() {
    }

	
    public Transaksis(Date tanggalTransaksi) {
        this.tanggal_transaksi = tanggalTransaksi;
    }
    public Transaksis(Date tanggalTransaksi, Integer total_harga) {
       this.tanggal_transaksi = tanggalTransaksi;
       this.total_harga = total_harga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTanggal_transaksi() {
        return this.tanggal_transaksi;
    }
    
    public void setTanggal_transaksi(Date tanggal_transaksi) {
        this.tanggal_transaksi = tanggal_transaksi;
    }
    public Integer getTotalHarga() {
        return this.total_harga;
    }
    
    public void setTotalHarga(Integer totalHarga) {
        this.total_harga = totalHarga;
    }
    public List<TransaksiDetails> getTransaksiDetailses() {
        return this.transaksiDetailses;
    }
    
    public void setTransaksiDetailses(List<TransaksiDetails> transaksiDetailses) {
        this.transaksiDetailses = transaksiDetailses;
    }




}


