package Model;
// Generated Feb 28, 2018 5:01:05 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;




/**
 * TransaksiDetails generated by hbm2java
 */
@Entity
@Table(name = "transaksi_details")
public class TransaksiDetails {


     @Id
     @GeneratedValue(strategy=GenerationType.AUTO)
     private Integer id;
     @OneToOne(fetch = FetchType.EAGER)
     @JoinColumn(name = "barang_id")
     private Barangs barangs;
     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "transaksi_id")
     private Transaksis transaksis;
     private int jumlah_barang;
     private int total_harga;

    public TransaksiDetails() {
    }

	
    public TransaksiDetails(int jumlahBarang, int totalHarga) {
        this.jumlah_barang = jumlahBarang;
        this.total_harga = totalHarga;
    }
    public TransaksiDetails(Barangs barangs, Transaksis transaksis, int jumlahBarang, int totalHarga) {
       this.barangs = barangs;
       this.transaksis = transaksis;
       this.jumlah_barang = jumlahBarang;
       this.total_harga = totalHarga;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Barangs getBarangs() {
        return this.barangs;
    }
    
    public void setBarangs(Barangs barangs) {
        this.barangs = barangs;
    }
    public Transaksis getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Transaksis transaksis) {
        this.transaksis = transaksis;
    }
    public int getJumlah_barang() {
        return this.jumlah_barang;
    }
    
    public void setJumlah_barang(int jumlah_barang) {
        this.jumlah_barang = jumlah_barang;
    }
    public int getTotal_harga() {
//        System.out.println("Model.TransaksiDetails.getTotal_harga()" + barangs.getHarga());
        return jumlah_barang * barangs.getHarga();
    }
    
    public void setTotal_harga(int total_harga) {
        this.total_harga = total_harga;
    }




}


